# **Olist E-commerce Data Preprocessing**

## **Data Dictionary**

 1. **olist_customers_dataset.csv**
- customer_id: unique identifier for each customer
- customer_unique_id: unique identifier for each customer (anonymized)
- customer_zip_code_prefix: zip code prefix of the customer's address
- customer_city: city where the customer is located
- customer_state: state where the customer is located


 2. **olist_geolocation_dataset.csv**
- geolocation_zip_code_prefix: zip code prefix for the location
- geolocation_lat: latitude of the location
- geolocation_lng: longitude of the location
- geolocation_city: city of the location
- geolocation_state: state of the location


 3. **olist_orders_dataset.csv**
- order_id: unique identifier for each order
- customer_id: unique identifier for the customer who placed the order
- order_status: current status of the order (e.g. delivered, shipped, canceled)
- order_purchase_timestamp: date and time when the order was placed
- order_approved_at: date and time when the payment for the order was approved
- order_delivered_carrier_date: date and time when the order was handed over to the carrier
- order_delivered_customer_date: date and time when the order was delivered to the customer
- order_estimated_delivery_date: estimated date when the order is expected to be delivered


 4. **olist_order_items_dataset.csv**
- order_id: unique identifier for the order
- order_item_id: unique identifier for each item within an order
- product_id: unique identifier for the product being ordered
- seller_id: unique identifier for the seller who listed the
- product shipping_limit_date: date and time when the seller has to ship the product
- price: price of the product
- freight_value: shipping fee for the product


 5. **olist_order_payments_dataset.csv**
- order_id: unique identifier for the order
- payment_sequential: index number for each payment made for an order
- payment_type: type of payment used for the order (e.g. credit card, debit card, voucher)
- payment_installments: number of installments in which the payment was made
- payment_value: value of the payment made


 6. **olist_products_dataset.csv**
- product_id: unique identifier for each product
- product_category_name: name of the category that the product belongs to
- product_name_lenght: number of characters in the product name
- product_description_lenght: number of characters in the product description
- product_photos_qty: number of photos for the product
- product_weight_g: weight of the product in grams
- product_length_cm: length of the product in centimeters
- product_height_cm: height of the product in centimeters
- product_width_cm: width of the product in centimeters


 7. **olist_sellers_dataset.csv**
- seller_id: unique identifier for each seller
- seller_zip_code_prefix: zip code prefix for the seller's location
- seller_city: city where the seller is located
- seller_state: state where the seller is located


 8. **product_category_name_translation.csv**
- product_category_name: name of the product category in Portuguese
- product_category_name_english: name of the product category in English


 9. **olist_order_reviews_dataset.csv**
- review_id: unique identifier for each review
- order_id: unique identifier for the order that the review is associated with
- review_score: numerical score (1-5) given by the customer for the product
- review_comment_title: title of the review comment
- review_comment_message: text of the review comment
- review_creation_date: date and time when the review was created
- review_answer_timestamp: date and time when the seller responded to the review (if applicable)

## **Data Preprocessing**

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
base_path = '/content/drive/MyDrive/olist_project/'

### **1. Import Library**

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import csv

### **2. Load all Datasets**

In [ ]:
customers = pd.read_csv(base_path + 'olist_customers_dataset.csv')
geolocation = pd.read_csv(base_path + 'olist_geolocation_dataset.csv')
order_items = pd.read_csv(base_path + 'olist_order_items_dataset.csv')
order_payments = pd.read_csv(base_path + 'olist_order_payments_dataset.csv')
order_reviews = pd.read_csv(base_path + 'olist_order_reviews_dataset.csv')
orders = pd.read_csv(base_path + 'olist_orders_dataset.csv')
products = pd.read_csv(base_path + 'olist_products_dataset.csv')
sellers = pd.read_csv(base_path + 'olist_sellers_dataset.csv')
category_translation = pd.read_csv(
    base_path + 'product_category_name_translation.csv'
)

In [ ]:
customers.head()

,customer_id,customer_unique_id,customer_zip_code_prefix,customer_city,customer_state
0,06b8999e2fba1a1fbc88172c00ba8bc7,861eff4711a542e4b93843c6dd7febb0,14409,franca,SP
1,18955e83d337fd6b2def6b18a428ac77,290c77bc529b7ac935b93aa66c333dc3,9790,sao bernardo do campo,SP
2,4e7b3e00288586ebd08712fdd0374a03,060e732b5b29e8181a18229c7b0b2b5e,1151,sao paulo,SP
3,b2b6027bc5c5109e529d4dc6358b12c3,259dac757896d24d7702b9acbbff3f3c,8775,mogi das cruzes,SP
4,4f2d8ab171c80ec8364f7c12e35b23ad,345ecd01c38d18a9036ed96c73b8d066,13056,campinas,SP

In [ ]:
geolocation.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1037,-23.545621,-46.639292,sao paulo,SP
1,1046,-23.546081,-46.644820,sao paulo,SP
2,1046,-23.546129,-46.642951,sao paulo,SP
3,1041,-23.544392,-46.639499,sao paulo,SP
4,1035,-23.541578,-46.641607,sao paulo,SP

In [ ]:
order_items.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14

In [ ]:
order_payments.head()

,order_id,payment_sequential,payment_type,payment_installments,payment_value
0,b81ef226f3fe1789b1e8b2acac839d17,1,credit_card,8,99.33
1,a9810da82917af2d9aefd1278f1dcfa0,1,credit_card,1,24.39
2,25e8ea4e93396b6fa0d3dd708e76c1bd,1,credit_card,1,65.71
3,ba78997921bbcdc1373bb41e913ab953,1,credit_card,8,107.78
4,42fdf880ba16b47b59251dd489d4441a,1,credit_card,2,128.45

In [ ]:
order_reviews.head()

,review_id,order_id,review_score,review_comment_title,review_comment_message,review_creation_date,review_answer_timestamp
0,7bc2406110b926393aa56f80a40eba40,73fc7af87114b39712e6da79b0a377eb,4,NaN,NaN,2018-01-18 00:00:00,2018-01-18 21:46:59
1,80e641a11e56f04c1ad469d5645fdfde,a548910a1c6147796b98fdf73dbeba33,5,NaN,NaN,2018-03-10 00:00:00,2018-03-11 03:05:13
2,228ce5500dc1d8e020d8d1322874b6f0,f9e4b658b201a9f2ecdecbb34bed034b,5,NaN,NaN,2018-02-17 00:00:00,2018-02-18 14:36:24
3,e64fb393e7b32834bb789ff8bb30750e,658677c97b385a9be170737859d3511b,5,NaN,Recebi bem antes do prazo estipulado.,2017-04-21 00:00:00,2017-04-21 22:02:06
4,f7c4243c7fe1938f181bec41a392bdeb,8e6bfb81e283fa7e4f11123a3fb894f1,5,NaN,Parabéns lojas lannister adorei comprar pela I...,2018-03-01 00:00:00,2018-03-02 10:26:53

In [ ]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18 00:00:00
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13 00:00:00
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04 00:00:00
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15 00:00:00
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26 00:00:00

In [ ]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0

In [ ]:
sellers.head()

,seller_id,seller_zip_code_prefix,seller_city,seller_state
0,3442f8959a84dea7ee197c632cb2df15,13023,campinas,SP
1,d1b65fc7debc3361ea86b5f14c68d2e2,13844,mogi guacu,SP
2,ce3ad9de960102d0677a81f5d0bb7b2d,20031,rio de janeiro,RJ
3,c0f3eea2e14555b6faeea3dd58c1b1c3,4195,sao paulo,SP
4,51a04a8a6bdcb23deccc82b0b80742cf,12914,braganca paulista,SP

In [ ]:
category_translation.head()

    product_category_name product_category_name_english
0            beleza_saude                 health_beauty
1  informatica_acessorios         computers_accessories
2              automotivo                          auto
3         cama_mesa_banho                bed_bath_table
4        moveis_decoracao               furniture_decor

In [ ]:
dfs = {
    "customers": customers,
    "geolocation": geolocation,
    "order_items": order_items,
    "order_payments": order_payments,
    "order_reviews": order_reviews,
    "orders": orders,
    "products": products,
    "sellers": sellers,
    "category_translation": category_translation
}

for name, df in dfs.items():
    print(f"\n=== {name.upper()} ===")
    print("Shape:", df.shape)
    print("\nMissing values:")
    print(df.isna().sum()[df.isna().sum() > 0])
    print("\nDuplicate:", df.duplicated().sum())
    print("\nData type:")
    print(df.dtypes)

=== CUSTOMERS ===
Shape: (99441, 5)

Missing values:
Series([], dtype: int64)

Duplicate: 0

Data type:
customer_id                 object
customer_unique_id          object
customer_zip_code_prefix     int64
customer_city               object
customer_state              object
dtype: object

=== GEOLOCATION ===
Shape: (1000163, 5)

Missing values:
Series([], dtype: int64)

Duplicate: 261831

Data type:
geolocation_zip_code_prefix      int64
geolocation_lat                float64
geolocation_lng                float64
geolocation_city                object
geolocation_state               object
dtype: object

=== ORDER_ITEMS ===
Shape: (112650, 7)

Missing values:
Series([], dtype: int64)

Duplicate: 0

Data type:
order_id                object
order_item_id            int64
product_id              object
seller_id               object
shipping_limit_date     object
price                  float64
freight_value          float64
dtype: object

=== ORDER_PAYMENTS ===
Shape: (103886, 5)

Missing values:
Series([], dtype: int64)

Duplicate: 0

Data type:
order_id                 object
payment_sequential        int64
payment_type             object
payment_installments      int64
payment_value           float64
dtype: object

=== ORDER_REVIEWS ===
Shape: (99224, 7)

Missing values:
review_comment_title      87656
review_comment_message    58247
dtype: int64

Duplicate: 0

Data type:
review_id                  object
order_id                   object
review_score                int64
review_comment_title       object
review_comment_message     object
review_creation_date       object
review_answer_timestamp    object
dtype: object

=== ORDERS ===
Shape: (99441, 8)

Missing values:
order_approved_at                 160
order_delivered_carrier_date     1783
order_delivered_customer_date    2965
dtype: int64

Duplicate: 0

Data type:
order_id                         object
customer_id                      object
order_status                     object
order_purchase_timestamp         object
order_approved_at                object
order_delivered_carrier_date     object
order_delivered_customer_date    object
order_estimated_delivery_date    object
dtype: object

=== PRODUCTS ===
Shape: (32951, 9)

Missing values:
product_category_name         610
product_name_lenght           610
product_description_lenght    610
product_photos_qty            610
product_weight_g                2
product_length_cm               2
product_height_cm               2
product_width_cm                2
dtype: int64

Duplicate: 0

Data type:
product_id                     object
product_category_name          object
product_name_lenght           float64
product_description_lenght    float64
product_photos_qty            float64
product_weight_g              float64
product_length_cm             float64
product_height_cm             float64
product_width_cm              float64
dtype: object

=== SELLERS ===
Shape: (3095, 4)

Missing values:
Series([], dtype: int64)

Duplicate: 0

Data type:
seller_id                 object
seller_zip_code_prefix     int64
seller_city               object
seller_state              object
dtype: object

=== CATEGORY_TRANSLATION ===
Shape: (71, 2)

Missing values:
Series([], dtype: int64)

Duplicate: 0

Data type:
product_category_name            object
product_category_name_english    object
dtype: object

### **3. Preprocessing**

### **1). Cleaning ORDERS (konversi tipe data tanggal)**

In [ ]:
# membuat kolom baru: order_purchase_date
orders['order_purchase_timestamp'] = pd.to_datetime(
    orders['order_purchase_timestamp'],
    errors='coerce'
)

# menampilkan kolom tanggal aja tanpa timestamp

orders['order_purchase_date'] = (
    orders['order_purchase_timestamp'].dt.date
)

In [ ]:
date_cols = ['order_purchase_timestamp', 'order_approved_at',
             'order_delivered_carrier_date', 'order_delivered_customer_date',
             'order_estimated_delivery_date', 'order_purchase_date']

for col in date_cols:
    orders[col] = pd.to_datetime(orders[col], errors='coerce')

In [ ]:
orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,order_purchase_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017-10-02
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018-07-24
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018-08-08
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017-11-18
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018-02-13

In [ ]:
orders.dtypes

order_id                                 object
customer_id                              object
order_status                             object
order_purchase_timestamp         datetime64[ns]
order_approved_at                datetime64[ns]
order_delivered_carrier_date     datetime64[ns]
order_delivered_customer_date    datetime64[ns]
order_estimated_delivery_date    datetime64[ns]
order_purchase_date              datetime64[ns]
dtype: object

### **2). Cleaning PRODUCTS (isi kategori yang kosong & hapus baris yang kosong)**

In [ ]:
products['product_category_name'] = products['product_category_name'].fillna('unknown')
products = products.dropna(subset=['product_weight_g', 'product_length_cm',
                                     'product_height_cm', 'product_width_cm'])

In [ ]:
products = products.merge(category_translation, on='product_category_name', how = 'left')
products['product_category_name_english'] = products['product_category_name_english'].fillna('unknown')

In [ ]:
products.head()

,product_id,product_category_name,product_name_lenght,product_description_lenght,product_photos_qty,product_weight_g,product_length_cm,product_height_cm,product_width_cm,product_category_name_english
0,1e9e8ef04dbcff4541ed26657ea517e5,perfumaria,40.0,287.0,1.0,225.0,16.0,10.0,14.0,perfumery
1,3aa071139cb16b67ca9e5dea641aaa2f,artes,44.0,276.0,1.0,1000.0,30.0,18.0,20.0,art
2,96bd76ec8810374ed1b65e291975717f,esporte_lazer,46.0,250.0,1.0,154.0,18.0,9.0,15.0,sports_leisure
3,cef67bcfe19066a932b7673e239eb23d,bebes,27.0,261.0,1.0,371.0,26.0,4.0,26.0,baby
4,9dc1a7de274444849c219cff195d0b71,utilidades_domesticas,37.0,402.0,4.0,625.0,20.0,17.0,13.0,housewares

### **3). Cleaning ORDER_REVIEWS (isi komentar yang kosong dan konversi tanggal)**

In [ ]:
order_reviews['review_comment_title'] = order_reviews['review_comment_title'].fillna('')
order_reviews['review_comment_message'] = order_reviews['review_comment_message'].fillna('')

In [ ]:
order_reviews['review_creation_date'] = pd.to_datetime(order_reviews['review_creation_date'])
order_reviews['review_answer_timestamp'] = pd.to_datetime(order_reviews['review_answer_timestamp'])

In [ ]:
print(order_reviews.isna().sum())

review_id                  0
order_id                   0
review_score               0
review_comment_title       0
review_comment_message     0
review_creation_date       0
review_answer_timestamp    0
dtype: int64

In [ ]:
order_reviews[
    order_reviews['review_comment_title'].isna()
]

Empty DataFrame
Columns: [review_id, order_id, review_score, review_comment_title, review_comment_message, review_creation_date, review_answer_timestamp]
Index: []

In [ ]:
print(order_reviews[['review_comment_title', 'review_comment_message']].isna().sum())

review_comment_title      0
review_comment_message    0
dtype: int64

In [ ]:
print((order_reviews['review_comment_title'] == '').sum())
print((order_reviews['review_comment_message'] == '').sum())

87656
58247

In [ ]:
print(order_reviews.shape)

(99224, 7)

In [ ]:
order_reviews.iloc[14]

review_id                  9a0abbb668bafb95a6d2b05db43284c4
order_id                   d7bd0e4afdf94846eb73642b4e3e75c3
review_score                                              3
review_comment_title
review_comment_message
review_creation_date                    2017-04-30 00:00:00
review_answer_timestamp                 2017-05-03 00:02:22
Name: 14, dtype: object

In [ ]:
print(order_reviews['review_comment_message'].str.contains(r'[\r\n]', na=False).sum())

3852

In [ ]:
order_reviews[
    order_reviews['review_comment_message'].str.contains(r'[\r\n]', na=False)
].iloc[0]

review_id                                 4b49719c8a200003f700d3d986ea1a19
order_id                                  9d6f15f95d01e79bd1349cc208361f09
review_score                                                             4
review_comment_title
review_comment_message     Mas um pouco ,travando...pelo valor ta Boa.\r\n
review_creation_date                                   2018-02-16 00:00:00
review_answer_timestamp                                2018-02-20 10:52:22
Name: 12, dtype: object

In [ ]:
repr(order_reviews.loc[12, 'review_comment_message'])

"'Mas um pouco ,travando...pelo valor ta Boa.\\r\\n'"

In [ ]:
print(repr(order_reviews.loc[12, 'review_comment_message']))

'Mas um pouco ,travando...pelo valor ta Boa.\r\n'

In [ ]:
order_reviews['review_comment_title'] = (
    order_reviews['review_comment_title']
    .str.replace(r'[\r\n]+', ' ', regex=True)
)

order_reviews['review_comment_message'] = (
    order_reviews['review_comment_message']
    .str.replace(r'[\r\n]+', ' ', regex=True)
)

In [ ]:
print(order_reviews['review_comment_message'].str.contains(r'[\r\n]', na=False).sum())

0

### **4). Cleaning GEOLOCATION (aggregasi data duplikat)**

In [ ]:
geolocation_clean = geolocation.groupby('geolocation_zip_code_prefix').agg({
    'geolocation_lat': 'median',
    'geolocation_lng': 'median',
    'geolocation_city': lambda x: x.mode()[0] if not x.mode().empty else x.iloc[0],
    'geolocation_state': lambda x: x.mode()[0] if not x.mode().empty else x.iloc[0]
}).reset_index()

In [ ]:
geolocation_clean.head()

,geolocation_zip_code_prefix,geolocation_lat,geolocation_lng,geolocation_city,geolocation_state
0,1001,-23.550381,-46.634027,sao paulo,SP
1,1002,-23.548551,-46.635072,sao paulo,SP
2,1003,-23.548977,-46.635313,sao paulo,SP
3,1004,-23.549535,-46.634771,sao paulo,SP
4,1005,-23.549612,-46.636532,sao paulo,SP

In [ ]:
geolocation_clean.duplicated().sum()

np.int64(0)

### **5). Cleaning ORDER_ITEMS (konversi tanggal)**

In [ ]:
order_items['shipping_limit_date'] = pd.to_datetime(order_items['shipping_limit_date'])

### **4. Simpan semua data yang udah clean**

In [ ]:
customers.to_csv('clean_customers.csv', index=False)
geolocation_clean.to_csv('clean_geolocation.csv', index=False)
order_items.to_csv('clean_order_items.csv', index=False)
order_payments.to_csv('clean_order_payments.csv', index=False)
orders.to_csv('clean_orders.csv', index=False)
products.to_csv('clean_products.csv', index=False)
sellers.to_csv('clean_sellers.csv', index=False)
category_translation.to_csv('clean_category_translation.csv', index=False)

print("Semua tabel berhasil disimpan dalam format CSV terpisah.")

Semua tabel berhasil disimpan

In [ ]:
order_reviews.to_csv(
    "clean_order_reviews.csv",
    index=False,
    encoding="utf-8-sig",
    quoting=csv.QUOTE_ALL
)